/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/form/Button.vue')['default']
    ButtonSkill: typeof import('./src/components/form/ButtonSkill.vue')['default']
    ExpandTransition: typeof import('./src/components/home/ExpandTransition.vue')['default']
    Left: typeof import('./src/components/home/Left.vue')['default']
    RightScope: typeof import('./src/components/home/RightScope.vue')['default']
    RightSkill: typeof import('./src/components/home/RightSkill.vue')['default']
    RightTitle: typeof import('./src/components/home/RightTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
